security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        SuProfile\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:        [ROLE_AUTEUR, ROLE_MODERATEUR]       
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH] 

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: supinfo, roles: [ 'ROLE_ADMIN' ] }
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
            logout:
                path:   fos_user_security_logout
                target: /
                invalidate_session : false 
            remember_me:
                key:        %secret% 
        

    #access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }