<?php

namespace SuProfile\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * B2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class B2Repository extends EntityRepository
{
}