<?php

namespace SuProfile\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * B3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class B3Repository extends EntityRepository
{
}