<?php

namespace SuProfile\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * M2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class M2Repository extends EntityRepository
{
}