<?php

namespace SuProfile\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SuprofileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuprofileRepository extends EntityRepository
{
	public function getSelectList()
	{
		$qb = $this->createQueryBuilder('a');

		return $qb;
	}

	public function getSuprofile($userId, $nombreParPage, $page)
	{
		if ((int) $page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		$uId = $userId;

		$query = $this->createQueryBuilder('s')
					  ->leftJoin('s.image', 'i')
                      ->addSelect('i') 
					  ->leftJoin('s.user', 'u')
                      ->addSelect('u')
				      ->where('u= :userId')
				      ->setParameter('userId', $uId)
                      ->getQuery();
		
		$query->setFirstResult(($page-1) * $nombreParPage)
              ->setMaxResults($nombreParPage);

		return new Paginator($query);
	}
	
	public function getDownloads($nombreParPage, $page)
	{
		if ((int) $page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
	
		$query = $this->createQueryBuilder('a')
					  ->leftJoin('a.fichier', 'f')
                      ->addSelect('f')
					  ->where('f is not NULL')
                      ->orderBy('a.date', 'DESC')
                      ->getQuery();

		$query->setFirstResult(($page-1) * $nombreParPage)
              ->setMaxResults($nombreParPage);

		return new Paginator($query);
	}
}
